import { IMenu } from "@/presentation/menu/interfaces/menu.interface";

export const menuData: IMenu[] = [
  {
    id: 1,
    name: "Classic Burger",
    price: 18.5,
    ingredients: [
      "Pan brioche",
      "Carne de res",
      "Queso cheddar",
      "Lechuga",
      "Tomate",
    ],
    description:
      "Hamburguesa clásica con ingredientes frescos y salsa especial.",
    quantity: 1,
    isAvailable: true,
    image: "https://picsum.photos/600/400?random=1",
  },
  {
    id: 2,
    name: "Double Cheese Burger",
    price: 24.9,
    ingredients: [
      "Pan artesanal",
      "Doble carne",
      "Doble queso cheddar",
      "Pepinillos",
    ],
    description: "Hamburguesa doble con mucho queso y sabor intenso.",
    quantity: 1,
    isAvailable: true,
    image: "https://picsum.photos/600/400?random=2",
  },
  {
    id: 3,
    name: "Bacon BBQ Burger",
    price: 26.0,
    ingredients: ["Pan brioche", "Carne", "Tocineta", "Queso", "Salsa BBQ"],
    description: "Hamburguesa ahumada con tocineta crocante y salsa BBQ.",
    quantity: 1,
    isAvailable: true,
    image: "https://picsum.photos/600/400?random=3",
  },
  {
    id: 4,
    name: "Chicken Burger",
    price: 19.5,
    ingredients: [
      "Pan de papa",
      "Pollo crispy",
      "Lechuga",
      "Tomate",
      "Mayonesa",
    ],
    description: "Hamburguesa de pollo crujiente con vegetales frescos.",
    quantity: 1,
    isAvailable: true,
    image: "https://picsum.photos/600/400?random=4",
  },
  {
    id: 5,
    name: "Hot Dog Clásico",
    price: 12.0,
    ingredients: ["Pan", "Salchicha", "Mostaza", "Ketchup", "Papa chips"],
    description: "Perro caliente tradicional con toppings clásicos.",
    quantity: 1,
    isAvailable: true,
    image: "https://picsum.photos/600/400?random=5",
  },
  {
    id: 6,
    name: "Chili Dog",
    price: 16.5,
    ingredients: [
      "Pan",
      "Salchicha",
      "Chili con carne",
      "Queso cheddar",
      "Cebolla",
    ],
    description: "Hot dog con chili casero y queso derretido.",
    quantity: 1,
    isAvailable: true,
    image: "https://picsum.photos/600/400?random=6",
  },
  {
    id: 7,
    name: "Veggie Burger",
    price: 21.0,
    ingredients: [
      "Pan integral",
      "Medallón vegetal",
      "Aguacate",
      "Lechuga",
      "Tomate",
    ],
    description: "Opción vegetariana fresca y deliciosa.",
    quantity: 1,
    isAvailable: true,
    image: "https://picsum.photos/600/400?random=7",
  },
  {
    id: 8,
    name: "Mexican Burger",
    price: 25.5,
    ingredients: ["Pan brioche", "Carne", "Guacamole", "Jalapeños", "Queso"],
    description: "Hamburguesa con toque mexicano y sabor picante.",
    quantity: 1,
    isAvailable: false,
    image: "https://picsum.photos/600/400?random=8",
  },
  {
    id: 9,
    name: "Cheese Fries Dog",
    price: 17.0,
    ingredients: [
      "Pan",
      "Salchicha",
      "Papas fritas",
      "Queso cheddar",
      "Tocineta",
    ],
    description: "Hot dog cargado con papas y queso.",
    quantity: 1,
    isAvailable: true,
    image: "https://picsum.photos/600/400?random=9",
  },
  {
    id: 10,
    name: "Monster Burger",
    price: 32.0,
    ingredients: [
      "Pan doble",
      "Triple carne",
      "Queso",
      "Tocineta",
      "Aros de cebolla",
    ],
    description: "Hamburguesa gigante para los más hambrientos.",
    quantity: 1,
    isAvailable: true,
    image: "https://picsum.photos/600/400?random=10",
  },
];
